### ISSUE TITLE
Unable to backup, crash and refund

### ISSUE THREAD

**Issue by Hugoos** [ScarletStudy/DGS1-Android-Release#1]
I'm using BlueStacks 3, the IrisMobile app prompted me to accept removal of the original Japanese app of DGS. Once I did that it removed the app from BlueStacks and actually refunded the purchase amount, after that it crashed with an error that was something like: "Unable to backup".

####################
# Device Info      #
####################

board:              MSM8960
bootloader:         unknown
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             ghost
display:            KOT49H.G900FXXU1ANCE
hardware:           qcom
id:                 KOT49H
manufacturer:       motorola
model:              XT1052
product:            ghost_retasia
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        G900FXXU1ANCE
release:            4.4.2
sdkInt:             19
sdk:                Kitkat

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/sdcard/ScarletStudy/IrisMobile/error.log,
	/storage/sdcard/ScarletStudy/IrisMobile/Backups/Patch.obb,
	/storage/sdcard/ScarletStudy/IrisMobile/Backups/Vanilla.apk

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: True

Folders in Android/obb:
	/storage/sdcard/Android/obb/com.netmarble.lin2ws,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.12.jp.co.capcom.daigyakusai.obb,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/patch.11.jp.co.capcom.daigyakusai.obb

####################
# Error Message    #
####################

Failed to install the patched "The Great Ace Attorney".

####################
# Exception String #
####################

None

**Comment by an-error42** [comment]
Looks like uninstalling the game shortly after purchasing it will trigger the auto refund process.

Please follow the "Fixing Corrupted IrisMobile Data" steps from [IrisMobile page](https://scarletstudy.gq/irismobile/).

After that, try installing DGS again from play store, open the original game and make sure it boots to the title screen at least.  
After confirming that the original game works perfectly, please try using IrisMobile again.

**Comment by Hugoos** [comment]
Tried again following your instructions.
I get the same error at the same point, but the auto refund process didn't trigger this time.
The exact error is: "Couldn't backup "The Great Ace Attorney" data".

I had originally made sure it launched the Japanese version properly and this was the case both the first time and the second time that I checked it.

**Comment by an-error42** [comment]
`Couldn't backup "The Great Ace Attorney data"` seems like a different error from what you were getting before which was `Failed to install the patched "The Great Ace Attorney"`.

Can you please upload the `error.log` file from `/ScarletStudy/IrisMobile/error.log` please?

**Comment by Hugoos** [comment]
There are two errors, I think I initially only copied the last error, this one should be more useful. 
####################
# Device Info      #
####################

board:              MSM8960
bootloader:         unknown
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             ghost
display:            KOT49H.G900FXXU1ANCE
hardware:           qcom
id:                 KOT49H
manufacturer:       motorola
model:              XT1052
product:            ghost_retasia
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        G900FXXU1ANCE
release:            4.4.2
sdkInt:             19
sdk:                Kitkat


####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/sdcard/ScarletStudy/IrisMobile/error.log,
	/storage/sdcard/ScarletStudy/IrisMobile/Backups/Patch.obb,
	/storage/sdcard/ScarletStudy/IrisMobile/Backups/Vanilla.apk




####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA


####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: True

Folders in Android/obb:
	/storage/sdcard/Android/obb/com.netmarble.lin2ws,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.12.jp.co.capcom.daigyakusai.obb,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/patch.11.jp.co.capcom.daigyakusai.obb




####################
# Error Message    #
####################

Couldn't backup the "The Great Ace Attorney" data.


####################
# Exception String #
####################

System.IO.FileNotFoundException: /data/app/jp.co.capcom.daigyakusai-1.apk does not exist
File name: '/data/app/jp.co.capcom.daigyakusai-1.apk'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) <0x16549440 + 0x0039c> in <65f35d20616b44f29faceee980f24e8a>:0 
  at IrisMobile.PatchActivity.CopyApkAndVideo () <0x14908018 + 0x000cb> in <e3e18bb5f701449d8c0ead40bc828a39>:0

**Comment by an-error42** [comment]
What bluestacks version are you using (from About)?

It's very likely this is an issue related to that build of bluestacks (there are multiple KitKat builds).

Do you have access to an android device, or can you install another version of bluestacks?

**Comment by Hugoos** [comment]
Client Version: 3.55.70.1783
Engine Version: 3.55.70.1203

I'll try to get a newer version of Bluestacks 3

**Comment by Hugoos** [comment]
Couldn't find another version of Bluestacks 3, so got some version 4.30.50.1690 of Bluestacks 4. Game patched successfully and game is in English now. I'm assuming because this version wasn't called "Beta" that it doesn't contain the crash bug?

**Comment by an-error42** [comment]
I see, glad it worked in the end.

Unfortunately, we have little to no control over the odd behaviors of BlueStacks, especially the older versions. A certain version of Bluestacks 3 was used during the development, trying to check their website now it seems to be gone.

Sorry for the inconvenience.

I believe this issue is safe to close now, we will edit the info in our website to better reflect the situation.
