### ISSUE TITLE
crash upon installing great ace attorney on patch

### ISSUE THREAD

**Issue by AutomataVM** [ScarletStudy/DGS1-Android-Release#13]
### About your device
Samsung J7 neo black SM-J701M

**Android Version?**
8.1.0

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
nope

**Is your device rooted?** (If you don't know what this means, then most likely no)
nope

### Your issue

after downloading the data and uninstalling the game, when installing the great ace attorney the game crashes and tells me to close the app and try again. Here is the error log:

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              universal7870
bootloader:         J701MUBU5BRH8
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             j7velte
display:            M1AJQ.J701MUBU5BRH8
hardware:           samsungexynos7870
id:                 M1AJQ
manufacturer:       samsung
model:              SM-J701M
product:            j7velteub
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        J701MUBU5BRH8
release:            8.1.0
sdkInt:             27
sdk:                OMr1

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Patch.obb,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Vanilla.apk

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: True

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.juegosjpf.pong,
	/storage/emulated/0/Android/obb/com.nianticlabs.pokemongo,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.12.jp.co.capcom.daigyakusai.obb,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/patch.11.jp.co.capcom.daigyakusai.obb

####################
# Error Message    #
####################

"The Great Ace Attorney" has not been installed.

####################
# Exception String #
####################

None

**Comment by wabberz** [comment]
This might be a rare race condition. Can you check with any file explorer if the folder `sdcard:/Android/obb/jp.co.capcom.daigyakusai_patcherTmp` exists? If so, please delete it, reinstall the game via PlayStore and try again. If you don't have a file explorer installed, I recommend fx: https://play.google.com/store/apps/details?id=nextapp.fx

**Comment by AutomataVM** [comment]
I have no sd card, I installed everything  on the main storage, could that be an issue?

nevertheless, I found the folder, so I will proceed to delete it and try again.

**Comment by wabberz** [comment]
The internal storage is also called "sdcard" on Android for some reason, "internal sd card".

**Comment by AutomataVM** [comment]
made it! unistalling it and trying again made it work!

Thanks for the help, I'll close the isse :)

Btw, thanks for the hard job :D
