### ISSUE TITLE
Could not check data integrity

### ISSUE THREAD

**Issue by nykolion** [ScarletStudy/DGS1-Android-Release#15]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Nokia 8
**Android Version?**
8.1.0
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue
Hello, 

I installed the patch when it came out, the game was playable without problem, but yesterday when I tried to launch the patched game, it said something like it could not find the account linked to my purchase or something like it. 

I redownloaded the game, and got this error. I then tried uninstalling the game and the patch, downloading new version of the patch.. rebooting the phone, doing this in every order possible, but the problem still occurs.

The game was bought following the tutorial of your website, I still can download it anytime and the japanese version works fine.

I saw someone say to delete the sdcard:/Android/obb/jp.co.capcom.daigyakusai_patcherTmp file on another issue, so I tried it but it didn't change anything. Now this won't reappear when I install IrisMobile again.

Error log is : 

####################
# Device Info      #
####################

board:              MSM8998
bootloader:         unknown
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             NB1
display:            00WW_4_88J
hardware:           qcom
id:                 OPR1.170623.026
manufacturer:       HMD Global
model:              TA-1012
product:            TA-1012_00WW
tags:               release-keys
types:              user
user:               cm

codename:           REL
incremental:        00WW_4_88J
release:            8.1.0
sdkInt:             27
sdk:                OMr1

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/PatchState.json,
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Patch.obb

####################
# APK Info         #
####################

Is Installed:  True
Is Accessable: True
Apk Path:      /data/app/jp.co.capcom.daigyakusai-YlW0TpkyQ85JcEyG-x2QuA==/base.apk

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   True
Backup OBB Folder Exists: False

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.facebook.orca,
	/storage/emulated/0/Android/obb/com.nianticlabs.pokemongo,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai,
	/storage/emulated/0/Android/obb/jp.co.capcom.kenji1en

Files in Game OBB Folder:
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai/patch.11.jp.co.capcom.daigyakusai.obb

Files in Backup OBB Folder:
	None

####################
# Error Message    #
####################

Couldn't check the "The Great Ace Attorney" data integrity.

####################
# Exception String #
####################

System.IO.FileNotFoundException: Could not find file "/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Vanilla.apk"
File name: '/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Vanilla.apk'
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) <0xc61d0c7c + 0x005c8> in <65f35d20616b44f29faceee980f24e8a>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) <0xc61d0b3c + 0x00027> in <65f35d20616b44f29faceee980f24e8a>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
  at System.IO.File.OpenRead (System.String path) <0xc61d017c + 0x00047> in <65f35d20616b44f29faceee980f24e8a>:0 
  at IrisMobile.Helpers.GetSHA256Progress (Android.Content.Context context, System.String file, Android.Widget.ProgressBar bar) <0xc70ae07c + 0x000cf> in <e3e18bb5f701449d8c0ead40bc828a39>:0 
  at IrisMobile.PatchActivity.CheckVanillaFilesIntegrity () <0xc70a2bdc + 0x0014f> in <e3e18bb5f701449d8c0ead40bc828a39>:0

**Comment by wabberz** [comment]
Hm, it can't find the backup of the Japanese binary it needs to update the patch. Please remove the folder `sdcard:/ScarletStudy/IrisMobile` (only the IrisMobile folder, not the other one or you'll lose your saves).

Then uninstall DGS completely and make sure `sdcard:/Android/obb/jp.co.capcom.daigyakusai` is gone. Then reinstall it from PlayStore and try patching it again. This will probably fix your issue.

**Comment by nykolion** [comment]
It indeed fixed the issue the game works just fine now :)

Thank you a lot for your help
