### ISSUE TITLE
License error after deleting playstore local data

### ISSUE THREAD

**Issue by AutomataVM** [ScarletStudy/DGS1-Android-Release#16]
About your device
Samsung J7 neo black SM-J701M

Android Version?
8.1.0

Are you using a Custom ROM? (If you don't know what this means, then most likely no)
nope

Is your device rooted? (If you don't know what this means, then most likely no)
nope

Your issue

I had been playing the well so far and well until I deleted by accident my play store data, now the game won't boot up because I get the license error!

![screenshot_20181120-171530_the great ace attorney](https://user-images.githubusercontent.com/7575105/48800470-9a4b6400-ece8-11e8-8968-44541353d9b6.jpg)

I can still select the Japanese play store from my account. What should I do?

**Comment by wabberz** [comment]
How long has it been since you bought the game? Did you remove the account in you system settings and re-add it?

**Comment by AutomataVM** [comment]
two, three months ago. nope, I did not remove it either. The last thing I remember doing is deleting the play store data and cache

**Comment by wabberz** [comment]
Were other purchases invalidated as well? I'm not sure why this removed your license, but I guess you have multiple options to try:
- completely uninstall DGS, then reinstall and patch again
- **or** remove the Japanese account from your phone and then add it again
Let me know if any of these work.

**Comment by AutomataVM** [comment]
alright, I uninstalled irismobile and it did not bug me with the license anymore. I Will reinstall irismobile and try it again

**Comment by AutomataVM** [comment]
and... done! reinstalling it worked and it even saved my data!! Really convenient! Thanks again :)

**Comment by wabberz** [comment]
Glad it worked for you 😃 
Yes, we redirected the save games to `sdcard:/ScarletStudy/Saves/DGS1/` so they will survive uninstalling the game, since patching the binary broke cloud saving.
