### ISSUE TITLE
Can't start the second case, it keeps resetting

### ISSUE THREAD

**Issue by DrakeDarkHunter** [ScarletStudy/DGS1-Android-Release#17]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Bluestacks 4.32.90.1001

**Android Version?**
Not Sure

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No

**Is your device rooted?** (If you don't know what this means, then most likely no)
No

### Your issue

**Please describe the issue you are experiencing:**
The game resets it's randomly., it did this a few times during the first case, but I could manage it thanks to saving carefully and skipping dialogue.

However the game starting resetting specifically as soon as game play would start for the second case (after the opening and the animated cut-scene.) This means that I can't just save around it.

EDIT: I tested the 3rd case and the same thing happens. Specifically as soon as the animated cut-scene ends, the game would cut to the red disclaimer about the unfinished nature of the patch twice in quick succession. The game would then start from the beginning.

**Comment by an-error42** [comment]
I recently faced the same problem, and that was after updating my Bluestacks version to 4.32.75.1002, there was no such bug in older versions.

Seems like they released a new Bluestacks update (4.40.0), can you perhaps give this one a try?

We're actually researching the possibility of supporting another Android Emulator due to the myriad of bugs associated with using Bluestacks.

**Comment by DrakeDarkHunter** [comment]
I just updated to 4.40.0 but unfortunately that didn't help. Do you know what the last version that worked was? Would I be able to downgrade to an older edition?

**Comment by wabberz** [comment]
Try different settings, especially assigning more RAM to the VM.

**Comment by DrakeDarkHunter** [comment]
> Try different settings, especially assigning more RAM to the VM.

Tried that, didn't do anything unfortunately.

**Comment by DrakeDarkHunter** [comment]
I deleted my current bluestacks version and tried 4.30.50.1690 and that seems to have fixed the problem for now. You may want to warn people that any version of the bluestacks beyond that one won't work on your website.

Thank you an-error for helping me realise this was a bluestacks version issue and wabberz for chiming in as well.
