### ISSUE TITLE
License Error upon starting The Great Ace Attorney

### ISSUE THREAD

**Issue by ConnorSimmonds** [ScarletStudy/DGS1-Android-Release#19]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Vodafone V8

**Android Version?**
Android 7.1.1

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
Nope

**Is your device rooted?** (If you don't know what this means, then most likely no)
Nope

### Your issue
License Error upon starting The Great Ace Attorney

**Please describe the issue you are experiencing:**
When starting up The Great Ace Attorney (patched version), I'm locked into a continuous loop where it asks me to log into my Google Account that has purchased the game, as it can't confirm my purchase. I have confirmed I'm logged into my account, and uninstalling the patch shows there's no issue with playing the game normally. This error is the same as https://github.com/ScarletStudy/DGS1-Android-Release/issues/16, but uninstalling IrisMobile and reinstalling it did nothing. Following your second set of instructions (removing the JP account and adding it again) also did nothing. Considering how DGS works perfectly fine without the patch, I'm unwilling to uninstall the entire game just yet.

I have about 4 accounts plugged into my phone - with my JP account being the fourth - which might be contributing to the issue, but it had been working fine for about a week.

**Comment by wabberz** [comment]
Did you initiate the patch right after making the purchase? Does the original still work if you uninstall the patch via IrisMobile?

If an app is uninstalled within a certain timeframe of buying it from PlayStore, it will be refunded. Please check if that happened to you - it will only happen once, if you buy the game again it wont happen again.

**Comment by ConnorSimmonds** [comment]
The game was purchased about two weeks ago (and was working up to two days ago), and as mentioned, the original still works if I uninstall the patch via IrisMobile.

**Comment by ConnorSimmonds** [comment]
To add onto this, Google Play gives me the option to Open or Uninstall the game, and I can see I've bought it via my Order History.

**Comment by wabberz** [comment]
Well, this is a first. Just to be sure: did this patch ever work on this phone?

You said you're reluctant to uninstall the game - is there a reason for that? Google Play will show Open/Uninstall even for refunded apps, so I'm afraid that doesn't help.

When did you last try if the vanilla (unmodified) version works?

**Comment by ConnorSimmonds** [comment]
I'm completely sure - I completed the first case on this phone.

It's mainly because it'll take a bit of time to do so - last time, it took me about 30ish minutes to uninstall/reinstall for the refund process (as per the instructions on your site), so I'd like to avoid that if possible. If it's needed, or you want me to do it as there's no other avenues, I am willing.

I last tried the vanilla just before making this issue, after uninstalling the patch for the first time. I was able to start up the game and reach the main menu without issue.

**Comment by wabberz** [comment]
Alright, so it worked but stopped working at some point. You mentioned you have 4 active Google accounts on this phone and that may be a factor. Could you try removing the 3 accounts that are unrelated to this app purchase?

**Comment by ConnorSimmonds** [comment]
That seems to have fixed it. If I had to guess, the license check wasn't looking through every Google Account, rather just the active one.

The only issue with this is that, obviously, my JP account is a throwaway - and having to remove/readd any needed accounts is a bit of a pain each time I want to play DGS.

**Comment by wabberz** [comment]
That does sound like a pain, yeah. You're the first person I've heard about using four accounts, though personally I'm using three without any issues so far... This does sound like an Android/PlayStore issue though, so I'm not sure how to help you...

**Comment by ConnorSimmonds** [comment]
Is there nothing in your patch that handles license checking? It could be that it's only looking through a certain amount of accounts - otherwise, it'd be good to bring it up to Google to see if there's anything on their end they can fix.

**Comment by wabberz** [comment]
We did not touch the license checking code in any way. Unlike the cloud saving feature, it still worked after we patched the binary, so there was no reason for us to remove or modify it. But it is indeed strange that the license check works for the vanilla version but not for our patch.

**Comment by ConnorSimmonds** [comment]
Weird.

I've added my accounts back, and it seems to work without issue. Worst comes to worse, make a disclaimer that more than three accounts seem to not work, or there may be issues.

**Comment by wabberz** [comment]
I will make note of that, thanks! Hope you can play the rest of the game without issues...
