### ISSUE TITLE
Problems with latest version of Bluestacks 4

### ISSUE THREAD

**Issue by jonaho23** [ScarletStudy/DGS1-Android-Release#20]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Windows 10, Bluestacks 4.40.10.1013
**Android Version?**
7 (?)
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue

Game is installed fully and legally, and patched correctly, boots and goes to title. Everything works up until the very first animated cutscene. It plays fully, but the app crashes immediately after and restarts.
-Edit- The original Japanese version of the game seems to work fine.

**Comment by jonaho23** [comment]
Nevermind! Problem was solved by downgrading to Bluestacks 4.30.50.

**Comment by wabberz** [comment]
Glad you were able to fix it yourself 😅
