### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Lissyx3** [ScarletStudy/DGS1-Android-Release#22]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Amazon / Fire HD 10 (7th generation)
**Android Version?**
Fire OS, i think that is the equivalent of Android 5.1.1 (?)
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No I guess? But I manually installed the Google Play Store, since it's not available on Amazon tablets
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue
**Please describe the issue you are experiencing:**
There was no problem downloading and launching DGS on my tablet and downloading Iris worked out too, but after I installed the patch, the game suddenly has no sound, except for cracking noices... When I started a new game the cutscene had sound and voices, but that's it... I noticed that there was another issue report about having no sound, but my BGM and SE are both turned on in the options.
I'm sorry if there are any mistakes, my native language isn't English (I'm german)

**Comment by wabberz** [comment]
Don't worry, I'm German too 😅 

- Please install [Apk Analyzer](https://play.google.com/store/apps/details?id=sk.styk.martin.apkanalyzer), select "The Great Ace Attorney", and tell me the `Apk Path`.
- Then tap the green circle with the three white dots on the top right and select `Export APK` - please tell me if this results in an error or if not, if the file appears in the root of your internal storage.
- Bonus points if you can hash the APK and tell me its size.

**Comment by Lissyx3** [comment]
Thanks for the fast response, oder sollte ich danke sagen?
The Apk Path is: /mnt/asec/jp.co.capcom.daigyakusai-1/base.apk
I exported the Apk and I didn't get an error, but I am not sure where the root of my internal storage is located (sorry, I'm really bad at this...) but I couldn't find the file, so maybe it didn't appear?
And I guess no bonus points for me, because I don't even know how to hash... Do I need a special App for this? 
I hope my not very informative response can nevertheless help in resolving the issue

**Comment by wabberz** [comment]
Interesting... The root of your internal storage would be the the highest in the hierarchy (the "Hauptverzeichnis"):

Root
|-Android
|-Documents
|-Download
|-etc.

A file manager like [fx](https://play.google.com/store/apps/details?id=nextapp.fx) can display it. If you find it, you can tap and hold it for a second, then tap the three white dots on the top right, then tap the (i) symbol, then swipe left until you see `Checksum`, then `Calculate`. You don't necessarily have to do this, since we have an idea what it might be and are investigating right now.

**Comment by Lissyx3** [comment]
Oh yes, now I get it! And the file is actually in the root of my internal storage, right on top above documents and download in a newly created Apk Analyzer folder.
Sorry for the confusion! I hope this information can help in some way.
Also I'm really grateful that you guys take this so serious and that you are already looking for a solution... Thanks again!

**Comment by Lissyx3** [comment]
I actually managed to fix the problem myself! As I was looking through the apps in my storage, I noticed that TGAA was the only app which was partially installed on the SD card. So I just moved the game entirely to the internal storage and now it's working, no weird sounds and it was really laggy before too, that's also gone now!
Sorry for the trouble and thanks you for looking for a solution. 
I already started playing and one can really tell how much work went into the patch and also the translation in general.
I wish you all the best of luck finishing your work on the game, I'm looking forward to the rest!
(And in the meantime I hope I don't encounter any bug while playing through episodes 1-4 :D)

**Comment by wabberz** [comment]
That's really interesting, I didn't think of this. Can you elaborate on the "partial install"?

**Comment by Lissyx3** [comment]
The Amazon settings interface is a lot different from a typical android device, I think?
So when you open settings on your Amazon device and go to Apps > Manage Apps > TGAA (or any other app) there's an overview of how much storage the app takes up on your device and how much of that data+the app is in your internal storage and how much of that data+the app is on your SD card.
Saying that the TGAA was partially installed on the SD card might have been wrong, because when I look at the data splitting now, it's the same as before (about 20mb from the app on the device and 2gb on the SD card).
But right below the storage division there is a grey button where it says "move data to SD card". Before, when the game was laggy and the sound didn't work, the grey button read "move data to internal storage". So after pressing that button the problem was gone. I just misinterpreted the storage division above as "partially installed on the SD card" since the data is split.
So if I were to press that button again and move the game to the SD card, the problem with the sound would return, I guess. 
But I'm also kinda confused, since now it still says "2gb on SD card" even though I moved the game to the internal storage with the button below... But since it's working now, that doesn't really matter

**Comment by wabberz** [comment]
Some apps refer to the internal storage as "internal SD card" for some reason. But this is an interesting hint, thank you for sharing that.

**Comment by Lissyx3** [comment]
No problem at all! I hope that information can help the team in some way.

(Also I have a question that's a bit off topic, but are the system requirements for DGS 2 somehow higher than for DGS? I'm asking because I've already bought DGS 2 on the App Store, but the game won't launch on my Fire... It's just the Capcom Logo, then the screens goes blank and after that the app reboots automatically and shows the Capcom logo again. DGS 1 worked fine for me from the start.)

**Comment by wabberz** [comment]
Hm, the engine is the same, yes. DGS2 is a bit more buggy than DGS1 is though. There are a lot of complaints in the Japanese PlayStore about that (hence the lower rating, even though everyone agrees that DGS2 is better).

We managed to fix some bugs the original version has, but I'm not sure why it doesn't work on your device. We may have to investigate once our Android engineer has some time 😅

**Comment by Lissyx3** [comment]
I see... Well, if worse comes to worst I could try to play the game on my phone instead of my tablet, but there's still some time until you guys will start releasing english patches for dgs2, so maybe the problem resolves itself by then :)
