### ISSUE TITLE
IrisMobile gets stuck while downloading Video OBB patch on bluestacks

### ISSUE THREAD

**Issue by akasinan** [ScarletStudy/DGS1-Android-Release#25]
### About your device
PC running Bluestacks 4
**Device Manufacturer / Model or Emulator / Version??**
4.60.3.1001
**Android Version?**

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue
Iris Mobile appears to get stuck on a white screen
**Please describe the issue you are experiencing:**
When I try to patch the game with Iris the screen just goes white in the middle of  downloading the Video OBB patch and then nothing happens

![image](https://user-images.githubusercontent.com/28210537/55664144-75aae100-57de-11e9-9791-08228e2bc67b.png)

**Comment by quocwashere** [comment]
Hello, I am having the same problem as this person. When I tried it on Bluestacks, the screen went white as it downloaded the Video OBB patch. I also tried it on NoxAppPlayer and it also "IrisMobile has stopped working" during downloading the Video OBB patch as well. I am also including the bug report that I got when IrisMobile crashed on my Nox player.

[IrisMobile Bug Report.docx](https://github.com/ScarletStudy/DGS1-Android-Release/files/3050121/IrisMobile.Bug.Report.docx)

**Comment by wabberz** [comment]
@quocwashere akasinan was able to solve this issue by turning on virtualization in the BIOS. Could you check if that helps you as well?

**Comment by quocwashere** [comment]
Yeah, that worked.

**Comment by Superninfreak** [comment]
How do you enable virtualization? I'm having this same problem, although I'm using OSX.

**Comment by Superninfreak** [comment]
> @quocwashere akasinan was able to solve this issue by turning on virtualization in the BIOS. Could you check if that helps you as well?

How do you enable virtualization? I'm having this same problem, although I'm using OSX.

**Comment by Superninfreak** [comment]
Nevermind. I figured out how to get it to work. I needed to reset my PRAM settings. You can do that by shutting down the computer, and holding down Option+Command+P+R when booting back up.

**Comment by Superninfreak** [comment]
Wait the problem is back. I got the patch to work but then the uninstalling process made Google refund my copy, so I had to start over. And now that old problem with breaking while downloading the patches is back and I can't fix it. Any help?

**Comment by wabberz** [comment]
If this is a MacBook, maybe this could help? http://osxdaily.com/2017/01/08/disable-gpu-switching-macbook-pro/

**Comment by Superninfreak** [comment]
It's a Macbook Air, and it doesn't have that option.

**Comment by wabberz** [comment]
I'm sorry, it's been a while since I last had a Mac. Not sure what else could help...

It's weird that clearing the PRAM made it work temporarily...
