### ISSUE TITLE
Unable to patch

### ISSUE THREAD

**Issue by giachai** [ScarletStudy/DGS1-Android-Release#26]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Bluestacks

**Android Version?**

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No.

**Is your device rooted?** (If you don't know what this means, then most likely no)
No. 

### Your issue

**Please describe the issue you are experiencing:**

Have not been able to install the patch for a few months. IrisMobile will uninstall the Japanese version of Dai Gyakuten Saiban and not be able to install the English patch. 
The Japanese app was bought legally through Google Play and the files were not modified.
The error code is as follows:

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              MSM8974
bootloader:         unknown
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             hlteatt
display:            KOT49H.N900AUCUCMLG
hardware:           universal5420
id:                 KOT49H
manufacturer:       samsung
model:              SAMSUNG-SM-N900A
product:            hlteuc
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        N900AUCUCMLG
release:            4.4.2
sdkInt:             19
sdk:                Kitkat

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/sdcard/ScarletStudy/IrisMobile/error.log,
	/storage/sdcard/ScarletStudy/IrisMobile/Backups/Patch.obb,
	/storage/sdcard/ScarletStudy/IrisMobile/Backups/Vanilla.apk

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: True

Folders in Android/obb:
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.12.jp.co.capcom.daigyakusai.obb,
	/storage/sdcard/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/patch.11.jp.co.capcom.daigyakusai.obb

####################
# Error Message    #
####################

Failed to install the patched "The Great Ace Attorney".

####################
# Exception String #
####################

None

**Comment by wabberz** [comment]
Can you remove the folders `Android/obb/jp.co.capcom.daigyakusai_patcherTmp` and `ScarletStudy/IrisMobile` on your internal storage, then uninstall DGS and reinstall it? Then first try if the original works before patching it again.

**Comment by giachai** [comment]
I did this and confirmed the original worked, but at a certain point during the patch (downloading the video OBB I think) the screen will go white and go back to the main IrisMobile screen.

**Comment by wabberz** [comment]
See #25

**Comment by giachai** [comment]
I wasn't able to solve it that way but I'm no longer experiencing the issue.
Thank you anyway for your hard work and fast responses! ^^

**Comment by wabberz** [comment]
Can you tell us what solved it so we can help others with the same problem?

**Comment by giachai** [comment]
Ah, I ended up giving up on Bluestacks and was able to patch it on Nox after deleting the same folders.
