### ISSUE TITLE
case 5 freeze/crash

### ISSUE THREAD

**Issue by bweezl** [ScarletStudy/DGS1-Android-Release#28]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Google Pixel 2
**Android Version?**
9
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue

**Please describe the issue you are experiencing:**
Case 5
Investigation 2
At the very end of the day, there is the event at night in Hatch's Pawnshop.  After bringing the cop back to Hatch's shop, the screen fades to black, and then the clock/save layover fades as well.  Nothing I press on the screen after that continues the cutscene, and waiting for it to continue on its own doesn't work either.  So I can't get past this spot. :(  I tried to get past this three times and it freezes at the same spot every time.  Resetting my phone did not work.  It does not generate an error message.  I included screenshots.
![001](https://user-images.githubusercontent.com/49356434/55678524-5ccb2a00-58c9-11e9-9bcd-a3b74d2a4162.png)
![002](https://user-images.githubusercontent.com/49356434/55678527-5fc61a80-58c9-11e9-9a97-37d86684c7e3.png)
![003](https://user-images.githubusercontent.com/49356434/55678528-60f74780-58c9-11e9-997e-3e3cbb37c7c2.png)
![004](https://user-images.githubusercontent.com/49356434/55678529-62c10b00-58c9-11e9-8911-02a38e279aeb.png)
![005](https://user-images.githubusercontent.com/49356434/55678530-648ace80-58c9-11e9-9097-ba5108c87be8.png)

**Comment by an-error42** [comment]
I've got some updates regarding this issue. It seems like the game will freeze if it was trying to play a video under a specific resolution.

Someone who was facing the same issue in an emulator was able to solve it by setting the resolution to something lower than 1600x900.

I understand that real devices may not be able to do the same, however, some devices do indeed have the ability to change the resolution.

An example would be Samsung devices, here's a screenshot of the possible settings:

![Screenshot_20190407-161245_Settings](https://user-images.githubusercontent.com/35239724/55691231-9e7cd300-59a4-11e9-9030-a92443914f12.jpg)

Unfortunately, we don't have enough information yet if this is possible to do using other devices. So in this regard, I ask you to check if your device supports similar settings, and if it does, please test the aforementioned fix and let us know if this solved the video issue so we can inform the other users as well.

**Comment by bweezl** [comment]
Thanks for getting back to me so quickly!

I've been looking into this and as far as I can tell, there aren't any settings in my phone that will allow me to adjust screen resolution specifically.  I did try all of the Display Size settings, but none of them fixed the problem.  I'm going to keep looking, but I may not be able to do anything further without rooting my phone.  Sorry I couldn't bring back a more useful answer.

**Comment by Abelcru** [comment]
I have the same issue, using LDPlayer.

Already changed resolutions, cores used and memory, nothing seems to fix this in my case.

Update: Couldn't make it to work the emulator, so I decided to try it on my phone and it works fine there.

**Comment by wabberz** [comment]
Pushed update 2.4.0.1 which should fix this issue. Just open IrisMobile and apply the update. Please let me know if this fixes the issue for you @bweezl @Abelcru

**Comment by Abelcru** [comment]
Video plays normally now on the emulator "LDPlayer", issue has been fixed on my end. @wabberz

**Comment by bweezl** [comment]
It worked perfectly! @wabberz thank you so much!
