### ISSUE TITLE
Music and Sound Effects not working

### ISSUE THREAD

**Issue by darkblaw** [ScarletStudy/DGS1-Android-Release#3]
Whenever I turn on the music and sound effects, they're all replaced by white noise. The only time when white noise isn't used as music or sound is during an anime cutscene.

**Comment by an-error42** [comment]
Please provide the following info:

* Device model (Or the name and the version of the emulator if you're using one instead).
* The installed Android version.
* Is it a custom ROM?
* Is your device rooted?

Also, did you patch the game following our [Purchasing Guide](https://scarletstudy.gq/purchasing-guide/) and using [IrisMobile](https://scarletstudy.gq/irismobile/)?

**Comment by darkblaw** [comment]
The phone is a Samsung Galaxy S5, model number SM-G900T. The Android version is 6.0.1. It is not a custom ROM. The device is not rooted. And yes, I bought the game on the Japanese Play Store, and then used IrisMobile to patch the game. Note: the original Japanese app was not having sound issues.

**Comment by an-error42** [comment]
I see, thanks for reporting back.

Do you have a discord by any chance? You'll probably need to test some sort of a beta build to confirm the solution.

**Comment by darkblaw** [comment]
I do have a Discord. Darkblaw#1440

**Comment by an-error42** [comment]
Hello, I've sent you a friend request yesterday.

Alternatively, you can join [FTI Server](https://discord.gg/3nYQ9aG), there's a **#dai-gyakuten-saiban** channel there where we can offer live support.

**Comment by Hyarion-SS** [comment]
Issue reported resolved.
