### ISSUE TITLE
Could not backup Install Error

### ISSUE THREAD

**Issue by Nmanic** [ScarletStudy/DGS1-Android-Release#32]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Samsung/Galaxy Tab S2

**Android Version?**
7.0

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No

**Is your device rooted?** (If you don't know what this means, then most likely no)
No

### Your issue

**Please describe the issue you are experiencing:**
My issues began because of uninstalling the game through the patch which prompted a refund. I found that issue here and followed steps, but it seemed I had corrupted Iris data. When I followed steps here to uninstall that and restart the process, I ran into an error that said it could not create a backup.  Also, the game works fine in Japanese with no patch applied. Here is the error log.

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              universal5433
bootloader:         T817PVPU2CQE7
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             gts210ltespr
display:            NRD90M.T817PVPU2CQE7
hardware:           universal5433
id:                 NRD90M
manufacturer:       samsung
model:              SM-T817P
product:            gts210ltespr
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        T817PVPU2CQE7
release:            7.0
sdkInt:             24
sdk:                N

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Patch.obb,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Vanilla.apk

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: True

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.facebook.orca,
	/storage/emulated/0/Android/obb/com.nintendo.zaga,
	/storage/emulated/0/Android/obb/com.nintendo.zara,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.12.jp.co.capcom.daigyakusai.obb,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/patch.11.jp.co.capcom.daigyakusai.obb

####################
# Error Message    #
####################

Couldn't backup the "The Great Ace Attorney" data.

####################
# Exception String #
####################

System.IO.FileNotFoundException: /data/app/jp.co.capcom.daigyakusai-1/base.apk does not exist
File name: '/data/app/jp.co.capcom.daigyakusai-1/base.apk'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) <0x910dc440 + 0x0039c> in <49b384109a01448fb05a72227ca5edb4>:0 
  at IrisMobile.PatchActivity.CopyApkAndVideo () <0xa7708150 + 0x000cb> in <1251bae9a9f64f2dbf4ed196c08e1110>:0

**Comment by Nmanic** [comment]
I was able to get it to work after uninstalling and deleting every relevant file and starting from scratch. Sorry for starting this issue without trying this first!

**Comment by wabberz** [comment]
No worries, glad you were able to fix it
