### ISSUE TITLE
Can't patch the game?

### ISSUE THREAD

**Issue by Melviiis** [ScarletStudy/DGS1-Android-Release#34]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
BlueStacks Version 4.60.10.1067

**Android Version?**
Not sure what to answer here, but I'm using the BlueStacks emulator

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No.

**Is your device rooted?** (If you don't know what this means, then most likely no)
No.

### Your issue

**Please describe the issue you are experiencing:**

The IrisMobile app can't seem to finish the patching process. At some point during the "Downloading Video OBB Patch..." the app screen will just become completely white (https://imgur.com/a/V1wAFN7 here are some screenshots I took right before it became white each time). But that's it, it doesn't crash or close or finish the process. I don't know if this is normal or if I wait long enough it'll actually finish the process. I don't think so, which is why I'm posting here. I already tried doint the process described in "Fixing Corrupted IrisMobile Data" and also uninstalling the game, deleting the IrisMobile folder, uninstalling IrisMobile, closing BlueStacks and then opening it up again and reinstalling everything but it just seems to do that every time. Can you help me? 
Also, sorry if I filled anything the wrong way or if this is too long. Thanks in advance!

**Comment by wabberz** [comment]
Does the fix in issue #25 work for you?

**Comment by Melviiis** [comment]
It worked! Thank you so much! :D

**Comment by wabberz** [comment]
Nice, have fun playing!
