### ISSUE TITLE
Small case 5 typo

### ISSUE THREAD

**Issue by colindom** [ScarletStudy/DGS1-Android-Release#35]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Bluestacks
**Android Version?**
Latest Bluestacks version, though I doubt it matters
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
Nope
**Is your device rooted?** (If you don't know what this means, then most likely no)
Nope
### Your issue

**Please describe the issue you are experiencing:**
Just noticed a small typo during case 5, while pressing Chrogray in the first testimony of Trial 4.
![Sin título](https://user-images.githubusercontent.com/26392968/56009693-ad1dff80-5cae-11e9-9a98-c221e8c4f0f3.png)

**Comment by keksdee** [comment]
It's a British English thing 👀

**Comment by colindom** [comment]
Whoopsie, I'll make sure to google a bit better next time if anything comes up. Thanks!
