### ISSUE TITLE
I cannot install TGA 

### ISSUE THREAD

**Issue by glassandgears** [ScarletStudy/DGS1-Android-Release#41]
*TGAA, forgot the second A

### About your device

**Samsung / MODEL SM-T530 / Version 7.1.1**

**7.1.1**

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)

No

**Is your device rooted?** (If you don't know what this means, then most likely no)

No

### Your Issue

**Everything else goes swimmingly until I am asked to install TGAA. For some reason I cannot click the install button no matter how hard I press or where I press. If I press outside of the box it cancels and I have to repeat this process all over again, but it still won't let me press the install button.**

**Comment by wabberz** [comment]
Did you allow IrisMobile to install unknown apps when it started for the first time? You can check by holding the IrisMobile app and dragging it to the App Info field. There should be the `Install unknown apps` permission (probably under Advanced).

**Comment by glassandgears** [comment]
I fixed it! I had installed TGAA before but something happened when I tried to patch in case 1-5 and I had to reinstall it all over again. I got it working again.
