### ISSUE TITLE
I have to purchase the game (again) after uninstalling.

### ISSUE THREAD

**Issue by celeiwiS** [ScarletStudy/DGS1-Android-Release#43]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Oppo F5 (CPH1723)
**Android Version?**
7.1.1
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue

I got the License Error so I tried the method mentioned in Issue #2  but after uninstalling I can't download the game again because I have to buy it again even though I didn't get a refund.

Here is proof I actually bought the game.
![58790327_276621196549998_4117345423075573760_n](https://user-images.githubusercontent.com/50129323/56942471-83d5ee00-6b4d-11e9-9047-80c31a5cbd89.png)
![59582260_2180182732066601_5457725839082782720_n](https://user-images.githubusercontent.com/50129323/56942477-8afcfc00-6b4d-11e9-8ecf-4e88f1d6f94f.png)

**Comment by wabberz** [comment]
But your Order History says it was..?

**Comment by celeiwiS** [comment]
That was when I made sure the game was working properly before patching it, it did work so I uninstall it then reinstall then patch. After a couple of days I got the license error so I tried what was mentioned in Issue 2 and uninstall it again, except this time I can't download the game again because according to the playstore I didn't even bought the game.

**Comment by wabberz** [comment]
hm, if you log into your Japanese account on your PC, what does the green button say?

https://play.google.com/store/apps/details?id=jp.co.capcom.daigyakusai&hl=en&gl=jp

Make sure you're using your Japanese account on the top right.

**Comment by celeiwiS** [comment]
It says "Installed" even though I uninstall it from my phone but in the play store app it says "2,520".

**Comment by wabberz** [comment]
hm, can you try removing and then re-adding your Japanese account in your phone's settings?

**Comment by celeiwiS** [comment]
Did it just now, it still says "2,520"

**Comment by wabberz** [comment]
Did you try clearing the PlayStore cache as described in the guide?

**Comment by celeiwiS** [comment]
I kept trying clear data but I tried clearing cache just like you said but that doesn't seem to fix it. I also force stop it before clearing just like what the guide says.

**Comment by wabberz** [comment]
How many accounts are active on this phone? I heard too many can cause this issue...

**Comment by celeiwiS** [comment]
I had 7 when I got the error but I reduced it to 3 (japanese acc included) now.

**Comment by wabberz** [comment]
Wow, 7? Can you try removing all of them and then only adding the Japanese one back for now? When it works, you can add the other two again. In any case, this very much seems like an Android issue...

**Comment by celeiwiS** [comment]
That didn't fix it either unfortunately, I guess I'll just buy it again if I have the extra money. 

I'll leave this open incase anyone knows how to fix this.

**Comment by wabberz** [comment]
But on your PC it said you own it. I'm not sure what happens if you buy it again. It would be very unfair if you had to pay for it twice. Maybe ask Google what to do?

**Comment by celeiwiS** [comment]
I doubt the customer service outside japan can help me with this and I cant contact the japanese playstore since I don't understand japanese.

**Comment by wabberz** [comment]
I would try the normal Android support. I'll look into it after work.

**Comment by mschulze0** [comment]
I keep getting the exact same issue. When I remove the patch, the license error disappears and the game runs fine. I can only get the patched version to work by uninstalling everything, then triggering the installation of the Japanese version from my PC (because in the play store on my device there's just the price button instead of install) and then installing the patch. Then the patched version works for some hours before the license error appears again. 
And by the way: all my other purchases from the Japanese play store continue to work fine at all times. 

I'm on a Pixel 3 XL with the Android Q beta.

**Comment by Noctsomnia** [comment]
I am having a very similar problem. I followed all the steps and even played through chapter 1 with no issues.

Was playing on Bluestacks and ran into a launching error this morning so I decided to reinstall it. Retracing the same steps to make sure nothing goes wrong, but once I go to my account to install the game it says INSTALL but when I click it I am asked to repurchase the game. Even checking the purchase history its there, and even the yen I have left is in my account.

Tried my phone out to double check the account using the same steps and it still asks me to buy it again.

went to the japanese website and it says its installed in green.

I am at a loss for what to do. I'd buy it again but I don't know if that guarantees no issues will occur. don't want to throw money down the drain over it. 

I am primarily using Bluestacks to play the game. had no issues before.
![BlueStacks_ScreenShot2](https://user-images.githubusercontent.com/50223069/57116394-d9172880-6d22-11e9-9614-b50b8541c728.jpg)
![BlueStacks_ScreenShot1](https://user-images.githubusercontent.com/50223069/57116420-0237b900-6d23-11e9-9660-b4f6264ded12.jpg)
![BlueStacks_ScreenShot](https://user-images.githubusercontent.com/50223069/57116422-0532a980-6d23-11e9-9a8e-130d98dd1088.jpg)

This is the prompt for repurchase.
![BlueStacks_ScreenShot4](https://user-images.githubusercontent.com/50223069/57116460-44f99100-6d23-11e9-815c-1830fbac2318.jpg)

**Comment by Noctsomnia** [comment]
I am now able to install the game on my phone, but still unable to do so on Bluestacks. I am starting to think there is something up with the game being recognized as bought on Bluestacks but I am no expert. I don't know if other android emulators work with the game and patch but I might as well experiment.

**Comment by Noctsomnia** [comment]
Ok after uninstalling Bluestacks once again and ONLY singing in with the japanese google playstore account I am finally able to download the game. I read somewhere that it takes a day for Google to update purchased apps to be synced to your account for other devices that aren't the original, but I am not sure of the validity of that information.

Either way I am able to finally install it now.

**Comment by jamfor999** [comment]
I have had this issue before and it seemingly resolved itself. I have no idea why, though. Seems like a Play Store glitch.

FWIW when you go to repurchase it, which I tried, it won't charge you again and will just error saying you already own the content...

**Comment by mschulze0** [comment]
I think I identified the issue, at least for my system: i was running out of storage space which caused android to delete the application files for TGAA. So when starting the game it tried to re-download the application files but because the binary has been modified by the patch it couldn’t authenticate correctly with the play store server so it was giving me the license error. Maybe this helps other people too.

**Comment by celeiwiS** [comment]
I checked the playstore again and for some reason I can download the game again, didn't buy it, the problem just resolved itself just like jf352 said. Currently patching as of posting this and everything looks fine so far.

**Comment by celeiwiS** [comment]
Didn't get the license error this time and I can start from my save file, glad the problem fixed itself, I was about to watch a playthrough instead but thankfully I can play it myself.
