### ISSUE TITLE
Unable to find DGS on google play store

### ISSUE THREAD

**Issue by Andriko15** [ScarletStudy/DGS1-Android-Release#48]
I have a Samsung Galaxy S10, version 9

I seem to be unable to find DGS on the google play store even after following the measures shown on the purchase guide. Is there any common mistakes I might be making while trying to do this?

Sorry if this is a dumb question but I have tried multiple times times but it simply doesn't show up.

**Comment by wabberz** [comment]
I was just about to reply - so you worked it out?

**Comment by Andriko15** [comment]
No problem man, it seemed to work once I cleared my google data too as well as my play store data.
Thanks for the quick response. :)
