### ISSUE TITLE
Stuck on boot loop - game crashing to the home screen 

### ISSUE THREAD

**Issue by geodeath** [ScarletStudy/DGS1-Android-Release#5]
I have a Huawei P20 Pro and i bought the japanese game with a second account with japanese billing details. The game runs fine on its own but when patched, it will show the boot screen with the scarlet logo, then the same screen will swipe from right to left 2 or more times then it will crash to the home screen.

If i restore the original, it works fine again. Tried with the newest release. 

there is also another bug, where if the game is installed for less than 15 minutes, it will auto refund the purchase too, meaning people have to buy it twice and play through at least 15 minutes before they can patch. Not sure this can be disabled by IrisMobile but would be cool to communicate it at least, if not. :) Will try to attach an error log, connecting my phone now to look up the files.

It is not a rooted device so cannot send a tombstone crash file as suggested by Uwabami.

Just realised that the instructions about finding an error log in “/ScarletStudy/IrisMobile/error.log” is stricly for IrisMobile and not DGS1 so not sure where i go from here and how i can help to make this working :(

**Comment by an-error42** [comment]
There were multiple reports about the same issue from the same device.

A fix is already in motion, we will publish an update to the patch when it's ready (IrisMobile will detect that automatically).

Please keep DGS patched for now, you'll be able to use the updated patches later to fix the problem.

**Comment by geodeath** [comment]
Fantastic news! Thanks so much for the prompt response. Looking forward to it.

**Comment by an-error42** [comment]
A new update is now available that should fix this problem.

Simply start IrisMobile, and click on "Apply Patch" button again. This will install the new patch.

Let us know if this indeed fixed the bootloop you experienced before.

**Comment by an-error42** [comment]
There were numerous reports from users who had the same issue (the exact same, and not a similar one) that stated that the new patch update fixed the bootloop issue.

I'll close the issue for now, but let us know if the new patch didn't fix the bootloop you're experiencing and I'll reopen it again.

Thanks!

**Comment by geodeath** [comment]
Hi and thanks for the hard work. Indeed, the new release did fix the boot loop issue and now i am happily playing episode 1. I am still trying to understand how to fix another issue with my particular phone (the screen is 'offset' a bit due to the notch, so i cannot see say an inch or 2 on the right side) but obviously this has nothing to do with your work :D Many thanks!

**Comment by an-error42** [comment]
Can you open a new issue about the screen bug, please? 

One of our team members had such issue and he fixed it by editing some parameters in Developer Options. We can help you solve your issue if you explained it in more details.

Thanks!
