### ISSUE TITLE
Game slowed and audio slowed and distorted

### ISSUE THREAD

**Issue by Inuyashafrost7** [ScarletStudy/DGS1-Android-Release#51]
### About your device

**Device Manufacturer / Model or Emulator / Version??**Samsung/ Galaxy Note 4/N910V.06

**Android Version?**
6.0.1
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)no

**Is your device rooted?** (If you don't know what this means, then most likely no)no

### Your issue After patching the Game runs slow and the sound is slow and distorted

**Please describe the issue you are experiencing:** I bough the game a few hours ago, played the title, audio was fine, speed was fine. Used the latest Iris Mobile to patch the game, and the audio distorts and slows and the game slows. I do not have the game installed to the SD card.

**Comment by wabberz** [comment]
Did you manage to fix it? If so, how?

**Comment by Inuyashafrost7** [comment]
Multiple reinstalls and patches. At one point, everything just worked

**Comment by wabberz** [comment]
Weird, IrisMobile is supposed to hash files to make sure they are correct when it's done... We'll look into this, thanks!

**Comment by Inuyashafrost7** [comment]
I will say, Iris mobile did not only crash and had to be reinstalled itself, but it also did not install the game correctly after patch adleast twice for me.
