### ISSUE TITLE
stuck on the scarlet study screen

### ISSUE THREAD

**Issue by Felersio** [ScarletStudy/DGS1-Android-Release#53]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Galaxy J6+
**Android Version?**
yes
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
no
**Is your device rooted?** (If you don't know what this means, then most likely no)
no
### Your issue
stuck on the scarlet study screen
**Please describe the issue you are experiencing:**
for some reason, my DGS is not running on my phone, its just stuck on the Scarlet Study screen. Has anyone encountered this problem? And if so, how do you solve this?

**Comment by wabberz** [comment]
"Android Version" means the version number of the Android OS. Like Android Nougat/Oreo/Pie or 7.0/8.0/9.0...

Did IrisMobile throw any error while patching? Did the Japanese original work without issues?

**Comment by wabberz** [comment]
No reply, closing.
