### ISSUE TITLE
Error Saying Data Cannot Be Backed Up

### ISSUE THREAD

**Issue by RevivalProject** [ScarletStudy/DGS1-Android-Release#54]
### About your device

**Device Manufacturer / Model or Emulator / Version??** Samsung 5 

**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0) 6.0.1

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no) Nope

**Is your device rooted?** (If you don't know what this means, then most likely no)
Nope 
### Your issue
I’ve tried to install DSG on my Samsung and every time I uninstall it from IrisMobile, it says the data can’t be backed up. I made sure the game loaded fine before I went to IrisMobile and I went on the discord and the person who tied to help me said to delete the IrisMobile folder and the DGS obb file which I already tried and it still doesn’t work. I even reinstalled everything and still nothing. Here’s the bug report:
####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              MSM8974
bootloader:         G900W8VLU1DQB2
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             kltecan
display:            MMB29M.G900W8VLU1DQB2
hardware:           qcom
id:                 MMB29M
manufacturer:       samsung
model:              SM-G900W8
product:            kltevl
tags:               release-keys
types:              user
user:               dpi

codename:           REL
incremental:        G900W8VLU1DQB2
release:            6.0.1
sdkInt:             23
sdk:                M

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
 /storage/emulated/0/ScarletStudy/IrisMobile/Backups/Patch.obb,
 /storage/emulated/0/ScarletStudy/IrisMobile/Backups/Vanilla.apk

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: True

Folders in Android/obb:
 /storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp

Files in Game OBB Folder:
 None

Files in Backup OBB Folder:
 /storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.11.jp.co.capcom.daigyakusai.obb,
 /storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/main.12.jp.co.capcom.daigyakusai.obb,
 /storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai_patcherTmp/patch.11.jp.co.capcom.daigyakusai.obb

####################
# Error Message    #
####################

Couldn't backup the "The Great Ace Attorney" data.

####################
# Exception String #
####################

System.IO.FileNotFoundException: /data/app/jp.co.capcom.daigyakusai-1/base.apk does not exist
File name: '/data/app/jp.co.capcom.daigyakusai-1/base.apk'
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) <0x9d5db440 + 0x0039c> in <49b384109a01448fb05a72227ca5edb4>:0 
  at IrisMobile.PatchActivity.CopyApkAndVideo () <0xb2928150 + 0x000cb> in <1251bae9a9f64f2dbf4ed196c08e1110>:0

**Comment by wabberz** [comment]
I assume you were able to get the help you needed on Discord. If not, feel free to re-open.
