### ISSUE TITLE
All my AA game voice blips are corrupted

### ISSUE THREAD

**Issue by YujiKyu** [ScarletStudy/DGS1-Android-Release#55]
### About your device

**Device Manufacturer / Model or Emulator / Version??**

Motorola 
MotoZ3

**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0)

9?

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no) 

No

**Is your device rooted?** (If you don't know what this means, then most likely no)

No 

### Your issue

I got DGS earlier today and installed the patch successfully but as I started playing the voice blips were kind of corrupted, which I thought was strange. I thought maybe it was just DGS's new Blip but then I opened DD and it sounded the same, SOJ was the same as well. My thoughts were that the patch somehow corrupted all the blips sound files for my games (every other sfx I've heard so far sounds normal including music)

This also might be the phone itselves issue I just got the phone a few days ago and haven't checked the games until now but I thought it was odd that it was just the blips that were corrupted   

Here's a video for reference https://photos.app.goo.gl/RgUbnUZkrkbDCdP77

Just bcus the video is from DD doesn't mean this isn't a DGS issue as DGS is affected and sounds the same.

Update: now no sound is playing from DGS, DD and SOJ text box is still corrupted

Update update: uninstalled the patch to see what would happen sounds back, text sfx is still corrupted

**Comment by wabberz** [comment]
This issue somehow got overlooked, but there is no way our patch influenced other games. The patcher doesn't even touch anything else and no system settings are changed. Closing.
