### ISSUE TITLE
Downloaded irismobile. Game doesn't work

### ISSUE THREAD

**Issue by JakeFTheDog** [ScarletStudy/DGS1-Android-Release#56]
### About your device

**Device Manufacturer / Model or Emulator / Version??** Huawei P20 Lite

**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0)
Android version 8.0.0

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No

**Is your device rooted?** (If you don't know what this means, then most likely no)
No

### Your issue
Download Irismobile to play TheGreatAceAttorny when I start it up I get the big report

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              ANE
bootloader:         unknown
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             HWANE
display:            ANE-LX1 8.0.0.159(C782)
hardware:           hi6250
id:                 HUAWEIANE-LX1
manufacturer:       HUAWEI
model:              ANE-LX1
product:            ANE-LX1
tags:               release-keys
types:              user
user:               test

codename:           REL
incremental:        159(C782)
release:            8.0.0
sdkInt:             26
sdk:                O

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log

####################
# APK Info         #
####################

Is Installed:  False
Is Accessable: False
Apk Path:      NA

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: False

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.ankama.tactilwar,
	/storage/emulated/0/Android/obb/com.boombox.fapceo,
	/storage/emulated/0/Android/obb/com.deemedyainc.duels,
	/storage/emulated/0/Android/obb/com.dragonest.autochess.google,
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.facebook.orca,
	/storage/emulated/0/Android/obb/com.frogmind.rumblestars,
	/storage/emulated/0/Android/obb/com.funtomic.matchmasters,
	/storage/emulated/0/Android/obb/com.habby.archero,
	/storage/emulated/0/Android/obb/com.moonactive.coinmaster,
	/storage/emulated/0/Android/obb/com.nianticlabs.hpwu.prod,
	/storage/emulated/0/Android/obb/com.nianticlabs.pokemongo,
	/storage/emulated/0/Android/obb/com.traplight.battleslides,
	/storage/emulated/0/Android/obb/com.versusevil.likeaboss

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	None

####################
# Error Message    #
####################

"The Great Ace Attorney" has not been installed.

####################
# Exception String #
####################

None
*Please describe the issue you are experiencing:**

**Comment by wabberz** [comment]
As described on our website, you need to install the original game first. IrisMobile will then patch it to the English version.

**Comment by JakeFTheDog** [comment]
How do I download the original game?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by henke37** [comment]
You buy it on the google playstore. The website has a [purchasing guide](https://scarletstudy.gq/purchasing-guide/). Try using it.
