### ISSUE TITLE
Screen display Samsung Galaxy S10

### ISSUE THREAD

**Issue by zeeuz** [ScarletStudy/DGS1-Android-Release#59]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Samsung Galaxy S10
**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0)
Pie
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue

**Please describe the issue you are experiencing:**
Before patching the game the screen display was fine. After patching it part of the game is out of the screen.
https://i.imgur.com/W7M9kHI.jpg

**Comment by wabberz** [comment]
In your Settings should be an option to force Full Screen or Immersion mode for DGS, can you try that to mitigate it?

**Comment by zeeuz** [comment]
That mostly fixed it, thanks!
