### ISSUE TITLE
Patch not applying

### ISSUE THREAD

**Issue by PhantomSA** [ScarletStudy/DGS1-Android-Release#6]
So I got the game from my friend who bought the game (I dunno if the patch will work in this case or not) aaand I got an error with the following details..

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              unknown
bootloader:         unknown
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             X556
display:            X556-H371A-N-180417V213
hardware:           mt6735
id:                 NRD90M
manufacturer:       Infinix
model:              Infinix HOT 4 Pro
product:            X556H371
tags:               release-keys
types:              user
user:               rlk-buildsrv34

codename:           REL
incremental:        1523950255
release:            7.0
sdkInt:             24
sdk:                N

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log

####################
# APK Info         #
####################

Is Installed:  True
Is Accessable: True
Apk Path:      /data/app/jp.co.capcom.daigyakusai-1/base.apk

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   True
Backup OBB Folder Exists: False

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.android.vending,
	/storage/emulated/0/Android/obb/com.discord,
	/storage/emulated/0/Android/obb/com.excelliance.dualaid.vend,
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.facebook.orca,
	/storage/emulated/0/Android/obb/com.google.android.gms,
	/storage/emulated/0/Android/obb/com.google.android.gsf,
	/storage/emulated/0/Android/obb/com.google.android.play.games,
	/storage/emulated/0/Android/obb/com.mojang.minecraftpe,
	/storage/emulated/0/Android/obb/com.ninjakiwi.btdadventuretime,
	/storage/emulated/0/Android/obb/com.tencent.ig,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai

Files in Game OBB Folder:
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai/main.11.jp.co.capcom.daigyakusai.obb,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai/patch.11.jp.co.capcom.daigyakusai.obb

Files in Backup OBB Folder:
	None

####################
# Error Message    #
####################

The installed "The Great Ace Attorney" is either unofficial or corrupted. Please make sure that you've installed "The Great Ace Attorney" from Google Play, and if you did, please try to download it again.

####################
# Exception String #
####################

None

**Comment by wabberz** [comment]
You tried to execute the patch with a modified version of the game. The patcher expects and only works with the unmodified version from PlayStore (that's how delta patching works) and it does not remove the PlayStore DRM present in the original game.

PlayStore does offer family sharing, but other than that - if the original game doesn't work, neither does the patch.

**Comment by an-error42** [comment]
As @wabberz said, IrisMobile expects the original APK and OBB files and will fail if the provided files were modified.

I doubt this is a backup of the original game since if it was indeed so, IrisMobile would've accepted it but the patched game (and so the original) will display a license error message.

Please consider buying the game from the PlayStore, we can't offer piracy-related support. Thank you.
