### ISSUE TITLE
IrisMobile White Blank Screen on Different Versions of Bluestacks

### ISSUE THREAD

**Issue by willrule488** [ScarletStudy/DGS1-Android-Release#62]
### About your device

**Device Manufacturer / Model or Emulator / Version??**
Bluestacks v4.130.1
**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0)
None
**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)
No
**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue
 The only issue is when the IrisMobile app doesn't give me the notice to uninstall the unmodified DGS app to reinstall it with the patch. Instead, I get a white blank screen. I tried other versions of Bluestacks 4 including Bluestacks v4.110 and Bluestacks v4.30 and they all have the same result. I also tried using Bluestacks' file manager and tried deleting the IrisMobile folder and redoing all the steps for the IrisMobile app, but I still get the same white screen. I managed to get the notice and was able to play the game on my phone, but for these versions of Bluestacks, or possibly any version of Bluestacks, it doesn't seem to work.
**Please describe the issue you are experiencing:**

**Comment by wabberz** [comment]
See #25

**Comment by willrule488** [comment]
Thank you so much, its works like it should.

**Comment by wabberz** [comment]
Nice!
