### ISSUE TITLE
Irismobile

### ISSUE THREAD

**Issue by Sans9955** [ScarletStudy/DGS1-Android-Release#65]
### About your device

**Device Manufacturer / Model or Emulator / Version??** Moto Z4

**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0)yes

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no)no

**Is your device rooted?** (If you don't know what this means, then most likely no)
No
### Your issue
An error in your irismobile
**Please describe the issue you are experiencing:** on my previous post I mentioned that I got dgs 2 because I got refunded straight after I patched dgs1  I thought I couldn't get it again but randomly I stumbled on my files and now apparently I have the 1st game so I tried to patch it and it says it couldn't and this is what the error says. Mind you I didn't even pirate the game I got it my own money so tell what to do please.

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              sm6150
bootloader:         MBM-3.0-foles_vzw-12f8e9d-190812
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             foles
display:            PDF29.105-25-20
hardware:           qcom
id:                 PDF29.105-25-20
manufacturer:       motorola
model:              moto z4
product:            foles_vzw
tags:               release-keys
types:              user
user:               hudsoncm

codename:           REL
incremental:        fb0f5
release:            9
sdkInt:             28
sdk:                28

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	/storage/emulated/0/ScarletStudy/IrisMobile/error.log,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Patch.obb,
	/storage/emulated/0/ScarletStudy/IrisMobile/Backups/Vanilla.apk

####################
# APK Info         #
####################

Is Installed:  True
Is Accessable: True
Apk Path:      /data/app/jp.co.capcom.daigyakusai-QlwIepQfjvEuh2DDVsKkVQ==/base.apk

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: False

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.netease.ddsfna,
	/storage/emulated/0/Android/obb/jp.co.capcom.daigyakusai2jp

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	None

####################
# Error Message    #
####################

"The Great Ace Attorney" Expansion files (OBBs) not detected. Your "The Great Ace Attorney" installation is corrupted.

####################
# Exception String #
####################

None

**Comment by wabberz** [comment]
You have a backup of the main game, but none of the extension files. Even if you had them, the game will verify the purchase on boot and fail to start.

**Comment by Sans9955** [comment]
Ah ok so even though I got it with my own money I need to delete it again and buy it again welp
