### ISSUE TITLE
"The Great Ace Attorney" Expansion Files Not Detected

### ISSUE THREAD

**Issue by GentlemanGamer94** [ScarletStudy/DGS1-Android-Release#66]
### About your device

**Device Manufacturer / Model or Emulator / Version??** Google Pixel 2- 64 GB

**Android Version?** (Kit Kat/Lollipop/Marshmallow/Nougat/Oreo/Pie or the number as in 7.1.0) Android 10- Oreo

**Are you using a Custom ROM?** (If you don't know what this means, then most likely no) no

**Is your device rooted?** (If you don't know what this means, then most likely no) no

### Your issue: I've followed the troubleshooting steps on the Scarlet Study site, and yet get the following issue as listed below:

**Please describe the issue you are experiencing:**

####################
# Version Info     #
####################

Code:7
Name: 1.1

####################
# Device Info      #
####################

board:              walleye
bootloader:         mw8998-002.0078.00
cpuAbi:             armeabi-v7a
cpuAbi2:            armeabi
device:             walleye
display:            QP1A.191005.007.A1
hardware:           walleye
id:                 QP1A.191005.007.A1
manufacturer:       Google
model:              Pixel 2
product:            walleye
tags:               release-keys
types:              user
user:               android-build

codename:           REL
incremental:        5908163
release:            10
sdkInt:             29
sdk:                29

####################
# App Info         #
####################

Data Folder Exists:       True

Files:
	

####################
# APK Info         #
####################

Is Installed:  True
Is Accessable: True
Apk Path:      /data/app/jp.co.capcom.daigyakusai-FXVFY6Yv9pL8cBSUUu0zhw==/base.apk

####################
# OBB Folder Info  #
####################

Android/obb Exists:       True
Game OBB Folder Exists:   False
Backup OBB Folder Exists: False

Folders in Android/obb:
	/storage/emulated/0/Android/obb/com.Level5.LaytonMJNA,
	/storage/emulated/0/Android/obb/com.Level5.LaytonMJNAsp,
	/storage/emulated/0/Android/obb/com.Level_5.MysteryRoomENG,
	/storage/emulated/0/Android/obb/com.facebook.katana,
	/storage/emulated/0/Android/obb/com.facebook.orca,
	/storage/emulated/0/Android/obb/com.nianticlabs.pokemongo,
	/storage/emulated/0/Android/obb/com.timeplay

Files in Game OBB Folder:
	None

Files in Backup OBB Folder:
	None

####################
# Error Message    #
####################

"The Great Ace Attorney" Expansion files (OBBs) not detected. Your "The Great Ace Attorney" installation is corrupted.

####################
# Exception String #
####################

None

**Comment by wabberz** [comment]
According to this log the game is not installed correctly. Does it run in Japanese?

**Comment by GentlemanGamer94** [comment]
I just checked and apparently, DGS didn't download fully/properly. Doing so
now; hopefully it'll work after that.

**Comment by GentlemanGamer94** [comment]
It seems to be working again, which is a little embarrassing; I thought that DGS had installed correctly and all was well, but it hadn't. Now that it has, the patching process is working smoothly again. Thanks a lot for your help!
