### ISSUE TITLE
Misused physics language

### ISSUE THREAD

**Issue by TheMrIron2** [ScarletStudy/DGS1-Android-Release#69]
### About your device

Bluestacks 
No custom ROM
No root

### Your issue

In Case 2, "inertia" is used to describe the latch closing shut due to the movement of the ship. However, inertia is a state of physical inaction or resistance to change in velocity (ie. movement), which is the opposite of what happened in the case. Perhaps it should be the _momentum_ from the ship's emergency stop that caused the latch to move.

It is mentioned multiple times towards the end of the case, but here is [one example](https://cdn.discordapp.com/attachments/609936121656508416/640902889291776029/SPOILER_Desktop_Screenshot_2019.11.04_-_13.18.37.53.png).

**Comment by Wendy-Youngbag** [comment]
I'm not a science person, so I'm having to make do with Google teaching me this stuff, but the original Japanese uses the word '慣性', literally 'intertia'. The problem seems to be more in how the lines were translated over the word itself, so I'll go ahead and edit them so they're correct.
