### ISSUE TITLE
British vocabulary issue

### ISSUE THREAD

**Issue by Moolano** [ScarletStudy/DGS1-Android-Release#70]
### About your device

**Device Manufacturer / Model or Emulator / Version??** The latest, I'm pretty sure

**Android Version?** Samsung Galaxy Tab

**Are you using a Custom ROM?** No

**Is your device rooted?** No

### Your issue

**Please describe the issue you are experiencing:**
In chapter 5, Gina calls Holmes a 'nonce' before running off. Holmes comments that he didn't expect her to call him an idiot. The thing is, that's not what that means. It's British slang for 'paedophile'. I've only found one dictionary with 'a stupid or worthless person' as a definition for it, and that was Wiktionary.

**Comment by wabberz** [comment]
This has been brought up before. None of our british members knew the word as such, our [glossary](https://scarletstudy.gq/british-dialect-glossary/) has it as _Idiot, Goof, Fool_. Our own research shows that this could be a regional variation, but I'm told in London (which is where Gina is from), it definitely does not mean what you said.
