### ISSUE TITLE
Case 3 typo

### ISSUE THREAD

**Issue by TheMrIron2** [ScarletStudy/DGS1-Android-Release#80]
### About your device

Bluestacks 
No custom ROM
No root

### Your issue

Typo in Case 3, during Lestrade's testimony. "Biassed" should be "biased".
[Screenshot](https://i.imgur.com/qNn9LQm.png) attached.

**Comment by wabberz** [comment]
See [translation notes](https://scarletstudy.gq/translation-notes/) for Episode 1-5.

**Comment by TheMrIron2** [comment]
My bad. Must have missed that.
