### ISSUE TITLE
Inconsistency in Case 2

### ISSUE THREAD

**Issue by Huzal** [ScarletStudy/DGS1-Android-Release#9]
In case 2 the Russian text on the floor is said to be the word "wardrobe" every time it is brought up by the characters (as well as in Vortex's office) but the court record states the word as "closet."

**Comment by Hyarion-SS** [comment]
Thanks -- this has been corrected.

**Comment by an-error42** [comment]
Fixed in 2.3.1 update which was published a few minutes ago.
